### ISSUE TITLE
Minor typos for first time `sdf init`

### ISSUE THREAD

**Issue by davidmasp** [vsbuffalo/scidataflow#1]
Hi Vince, I love the idea and I actually wanted to write something similar for a long while. Happy I don't have to now. (I am a bit new to rust but I can try help at some point down the line). Really good implementation and so far works flawlessly!

I started using it and I saw what might be a typo? (I installed it using `cargo install scidataflow`, version is `0.8.0`)

```
>>> sdf init
Error: No SciDataFlow config found at "<<HOME>>/.scidataflow_config". Please set with scf config --user <NAME> [--email <EMAIL> --affil <AFFILIATION>]
```

When running the suggested command it doesn't run because scf should be sdf and the `--user` param should be name (I think).

```
>>> scf config --user David
scf: command not found
``` 

I think it should say something like this:

```
Please set with sdf config --name <NAME> [--email <EMAIL> --affiliation <AFFILIATION>]
```

I think [these](https://github.com/vsbuffalo/scidataflow/blob/64985edb53ebd82da7ac9f9c6f033ca478ae4537/src/lib/project.rs#L109-L113) are the lines.

Best regards and thanks for building this!

**Comment by vsbuffalo** [comment]
Good catch, and thanks for reporting this! I've pushed 04c82e7 to the `main` branch which fixes this issue. Let me know if you have any other problems (or ideas!).
