### ISSUE TITLE
Download a file from figshare

### ISSUE THREAD

**Issue by jsalignon** [vsbuffalo/scidataflow#11]
Hi,
Thank for your package!
I was wondering. How can I download a file from a Figshare repository?
I have added my API personal token, but I am not sure how I can download a given file from a given figshare repository. Could you please provide an example?
Thanks,
Jerome

**Comment by vsbuffalo** [comment]
Hi Jerome,

Thanks so much for using SciDataFlow! 

Is the repository public? Currently if the repository has been made outside of SciDataFlow, it can be tricky to connect the two. So far, the main workflow is to handle repositories created by SDF. Still, it will be possible. The easiest solution of the repository is public is to just use `sdf get` with the URL of the data file you are using.

**Comment by vsbuffalo** [comment]
Hi Jerome, I am going to close this issue but please do reopen it if this solution did not work for you.

**Comment by jsalignon** [comment]
Hi Vince,
sdc get act like wget I presume. If I do that on a Figshare file I get a html file. Using the download link doesn't work either). 
For instance how would I download this text file from a public repository? https://figshare.com/articles/dataset/References_and_test_datasets_for_the_Cactus_pipeline/20171347?file=38269925
