### ISSUE TITLE
How to contribute to assets

### ISSUE THREAD

**Issue by apraga** [vsbuffalo/scidataflow#12]
Hi,

So far, I really like your project, thanks for your work. How would one goes about contributing to SciDataFlow-Assets to make a public asset ?
As it stands, it's an organization so I cannot figure out how to add a new repo there without having rights. If more people are interested, maybe making a PR where new contributors would comment to ask access would be an idea ?

Thanks,

**Comment by vsbuffalo** [comment]
Hi apraga!

Assets are commonly-used general interest community data sets. If your project fits that description, the best way to do it is to open up an issue here and point me to your repository and I can assess.

Note that if your project is more limited scope, we may not host it as an asset on the official scidataflow-assets organization page (which is meant for major data sets, etc), but that doesn't stop users from using your repository *as* an asset with:

```
sdf asset --github <url>
```

I hope this helps, and let me know if your project is general use enough that it should be hosted on SDF assets. 

Vince
