### ISSUE TITLE
`sdf mv` does not move data in new folders

### ISSUE THREAD

**Issue by apraga** [vsbuffalo/scidataflow#14]
Hi,

With the latest (? not sure how to check the version) scidataflow, I cannot move files. Steps to reproduce 

```bash
❯ sdf init
❯ sdf get https://raw.githubusercontent.com/SCAI-BIO/covid-data-catalogue/main/data/general.tsv
❯ mkdir mydir
❯ sdf mv general.tsv mydir/
Error: Error encountered when moving file.

Caused by:
    Not a directory (os error 20)
```

A temporary fix would be to move the file by hand , run `stdf status` and `sdf add` it back. Any idea would be great, thanks !

**Comment by vsbuffalo** [comment]
Thanks for finding and reporting this issue! I have addressed the problem.

**Comment by vsbuffalo** [comment]
Hi @apraga,

My apologies — I introduced a bug in accidentally introduced in solving this issue. I have just pushed version 0.8.9 to crates.io, so this version should have a `sdf mv` that is bug free. I have also added a new test to ensure that related do not crop up again. My apologies if this bug affected you!
