### ISSUE TITLE
Does every  sub-directory in an `sdf` project need to have its own remote?

### ISSUE THREAD

**Issue by mrvollger** [vsbuffalo/scidataflow#20]
Hi @vsbuffalo,

Does every sub-directory in an `sdf` project need to have its own remote? e.g. I have something that looks like this:
<img width="991" alt="image" src="https://github.com/vsbuffalo/scidataflow/assets/6935283/a276c5ff-e201-4793-b104-4e0c27bce615">
Currently I have `data` linked to the zenodo project but not `Rdata` or `Tables`. If I try to add Rdata or Tables I get errors, and if I try to link the base directory (`.`) then it won't let me `track` any files in any of the subdirectories. 

I just want to confirm that this would require three remotes even though it's one sdf project? and if so is it something you might consider changing to allow multiple subdirectories?

Cheers,
Mitchell

**Comment by vsbuffalo** [comment]
Hi Mitchell,

Thanks for using SciDataFlow! So unfortunately, a remote can only correspond to a single directory. This isn't a limitation of SciDataFlow, but rather of the remote data repositories which do not support nested data structures (at least at the time that I wrote SciDataFlow). 

I have been frustrated by this, so what I usually do is make a sort of "supplementary_data" directory that has all the files that you want to host on a remote eventually, as part of the supplementary data associated with the publication. Then, you can keep really large raw or intermediate data that you don't want to host on a remote in a separate directory. In your case it may be something like:

```
data/Rdata
data/supplementary_data/ > Zenodo
data/Tables
```

You can also create associate multiple directories with different remote repositories too. 

Hope this helps, and let me know if this workflow works for you.

Vince
