### ISSUE TITLE
Error linking to zenodo

### ISSUE THREAD

**Issue by Tomas-Pe** [vsbuffalo/scidataflow#24]
I am trying to link ScienceDataFlow (SDF) to Zenodo using the command:

`sdf link ./ zenodo <token< --name "project-name"
`
However, I am encountering the following error:
```
Error: error decoding response body: missing field `title` at line 1 column 277

Caused by:
    missing field `title` at line 1 column 277
```

I have generated and used a  personal access token for authentication.
I have already completed a previous initialization (sdf init).
I'm using Ubuntu 20.04

**Comment by apraga** [comment]
Hi,

I'm unable to reprodue your error on scidataflo 0.8.11.
Which version of scidataflow are you using ? Could you share data_manifest.yml ? Thanks

**Comment by vsbuffalo** [comment]
Hi Tomas-Pe,

I am also unable to replicate it — I will close this issue but please feel free to reopen it if the issue persists.
