### ISSUE TITLE
an `sdf rm` command?

### ISSUE THREAD

**Issue by andrewkennard** [vsbuffalo/scidataflow#3]
I'm playing around with scidataflow and I'm excited to see it in action! I added some files that I realize I don't necessarily want to be part of the data_manifest at the moment, but I noticed there wasn't a way to remove them programmatically. I'm guessing that I could just manually remove them from the YAML file in vim, but it might be nice to have a command to take care of that automatically. Especially something like `sdf rm *.bam` would be nice to remove all matching files in a folder, which currently works with `sdf add`.

Thanks!

**Comment by vsbuffalo** [comment]
Hi Andrew,

Thanks so much for the suggestion! I will work to add this feature this week. My feeling is that `sdf rm` should *only* remove it from the manifest, and not the file. Perhaps `sdf rm --also-delete` might also delete the file. What do you think?
